services:
  deploy:
    - name: label-studio-ml-backend
      dockerfile: Dockerfile
      ports:
        - target: 9090
          published: 9090
          protocol: tcp
      environment:
        - name: MODEL_DIR
          value: /data/models
        - name: WORKERS
          value: "2"
        - name: THREADS
          value: "4"
        - name: LOG_LEVEL
          value: DEBUG
        - name: ANY
          value: PARAMETER
      healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9090/health"]
        interval: 5s
        timeout: 20s
        retries: 10
      volumes:
        - source: label_studio_models
          target: /data/models
          type: volume
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      restart_policy:
        condition: unless-stopped

volumes:
  label_studio_models:
    name: label_studio_models