version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: humansignal/ml-backend:v0
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -f http://localhost:9090/health || exit 1'
      interval: 5s
      timeout: 20s
      retries: 3
    build: .
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
    ports:
      - "9090:9090"
