version: "3.8"
services:
  ml-backend:
    container_name: ml-backend
    build: 
      context: .
      dockerfile: Dockerfile
    image: ml-backend:latest
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9090/health"]
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - label_studio_models:/data/models
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    restart: unless-stopped

volumes:
  label_studio_models:
    name: label_studio_models