version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: humansignal/ml-backend:v0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]  # The ML backend returns 200 OK on root path
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s
    build: .
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
    ports:
      - "9090:9090"
